version: "3"
services:
  mongo:
    image: mongo # to be retrieved from dockerhub
    ports:
      - "27017:27017" # forward mongod port
  app:
    build: .
    #image: ma9dalen8/node-web-app
    ports:
      - "3000:3000" # forward webserver on standard-http port
    depends_on:
      - mongo
    # volumes:
    # - ./data:/data/db
    # find out where to mount to in the image's Dockerfile;
    #           here: https://github.com/docker-library/mongo/blob/00a8519463e776e797c227681a595986d8f9dbe1/3.0/Dockerfile
